language: php
php:
  - 5.6
cache:
  directories:
    - node_modules
    - vendor
before_script:
  - uname -a
  - pwd
  - ls -LR /etc
  - /home/travis/.phpenv/versions/5.6/bin/composer self-update
  - echo -e "Host 192.30.252.*\n\tStrictHostKeyChecking no\n\tUserKnownHostsFile=/dev/null\n\n" > ~/.ssh/config
  - cat ~/.ssh/config
  - sudo ./vagrant/nginx.sh $TRAVIS_BUILD_DIR
  - sudo ./vagrant/postgresql.sh
  - sudo ./vagrant/redis.sh
  - sudo ./vagrant/nodejs.sh
  - sudo ./vagrant/npmpackages.sh
  - sudo ./vagrant/php.sh
  - sudo ./vagrant/phalcon.sh $TRAVIS_BUILD_DIR
  - sudo npm install
script:
  - grunt phalcon --local

